language: php
php:
  - '7.1'

sudo: required
services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.13.0

before_install:
  - docker-compose -f docker/docker-compose.yml build
  - docker-compose -f docker/docker-compose.yml up -d
  - composer install --ignore-platform-reqs

script:
  - docker-compose -f docker/docker-compose.yml exec -T php-apache "vendor/bin/phpunit"
  - docker-compose -f docker/docker-compose.yml exec -T php-apache phpcs src --standard=PSR2