version: '3'

volumes:
  mysql_data:
    driver: local

services:
  application:
      container_name: application
      build: php-apache
      ports:
          - "80:80"
      volumes:
          - ./../:/var/www/html

  database:
      container_name: database
      image: mariadb
      ports:
          - "13306:3306"
      volumes:
          - "mysql_data:/var/lib/mysql"
      env_file: mysql.env
      restart: "on-failure"

